version: "3.9"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    expose:
      - $MONGODB_PORT
    volumes:
      - db:/data/db

  backend:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./models:/jedi/models
      - ./libs:/jedi/libs

  frontend:
    build: ./jedi-frontend
    restart: unless-stopped
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    volumes:
      - ./jedi-frontend/src:/opt/jedi-frontend/src
    env_file: ./.env
    environment:
      - BACKEND=backend
      - BACKEND_PORT=$NODE_DOCKER_PORT
volumes:
  db: