version: "3.9"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    expose:
      - $MONGODB_PORT
    volumes:
      - db:/data/db

  api:
    depends_on:
      - mongodb
    build: ./edji-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $API_PORT:80
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
      - PORT=80
    stdin_open: true
    tty: true
    volumes:
      - ./edji-api/models:/opt/edji-api/models
      - ./edji-api/libs:/opt/edji-api/libs
      - ./edji-api/openapi:/opt/edji-api/openapi

  frontend:
    build: 
      dockerfile: ./edji-frontend/Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - $FRONTEND_PORT:8080
      # - 9229:9229
    stdin_open: true
    tty: true
    volumes:
      - ./edji-frontend/src:/opt/edji-frontend/src
      - ./edji-frontend/package.json:/opt/edji-frontend/package.json
      # - ./docker_node_modules:/opt/edji-frontend/node_modules
    env_file: ./.env
    environment:
      - API_HOST=$API_HOST

volumes:
  db: